cmake_minimum_required(VERSION 3.10)
project(shim5)

option(SHARED_LIB "Build as a shared library" ON)
option(USE_STATIC_LIBS "Link with static libraries" OFF)
option(WANT_EXAMPLES "Build the examples" OFF)
option(WANT_TOOLS "Build the tools" OFF)
option(WANT_TTF "Build with TTF support" ON)
option(WANT_XML "Build with XML support" OFF)
option(WANT_ALLEGRO_TOOLS "Need Allegro to build these tools" OFF)
option(USE_VORBIS "Use libogg/libvorbis (needed for OGG/Vorbis)" ON)
option(USE_VORBISFILE "Use libvorbisfile on top of libogg/libvorbis" OFF)
option(USE_FLAC "Use FLAC for samples" ON)
option(USE_PNG "Support PNG images" on)
option(DBG "Debug build" OFF)

set(USER_INCLUDE_PATH "" CACHE FILEPATH "Any extra include directories you want")
set(USER_LIBRARY_PATH "" CACHE FILEPATH "Any extra library directories you want")

include_directories("glm")
include_directories("tgui6/include")
include_directories("include")
include_directories(${USER_INCLUDE_PATH})
link_directories(${USER_LIBRARY_PATH})

set(LIB_SRC
	src/a_star.cpp
	src/audio.cpp
	src/cd.cpp
	src/devsettings.cpp
	src/font.cpp
	src/shim.cpp
	src/flac.cpp
	src/gfx.cpp
	src/gui.cpp
	src/image.cpp
	src/input.cpp
	src/interp.cpp
	src/md5.cpp
	src/mml.cpp
	src/model.cpp
	src/pixel_font.cpp
	src/primitives.cpp
	src/sample.cpp
	src/shader.cpp
	src/sprite.cpp
	src/tilemap.cpp
	src/translation.cpp
	src/util.cpp
	src/vertex_cache.cpp
	src/vorbis.cpp
	src/widgets.cpp
	src/cpa.cpp
	src/error.cpp
	src/json.cpp
	src/mt19937ar.cpp
	src/tokenizer.cpp
	src/utf8.cpp
)

if(WANT_TTF)
	LIST(APPEND LIB_SRC src/ttf.cpp)
endif()
if(WANT_XML)
	LIST(APPEND LIB_SRC src/xml.cpp)
endif()

if(WIN32 AND SHARED_LIB)
	list(APPEND LIB_SRC versioninfo.rc)
endif()

set(SHIM_LIB shim5)
if(SHARED_LIB)
	add_library(${SHIM_LIB} SHARED ${LIB_SRC})
else()
	add_library(${SHIM_LIB} STATIC ${LIB_SRC})
endif()

if(WANT_EXAMPLES)
	add_executable(example examples/example.cpp)
endif()

if(WANT_TOOLS)
	add_executable(change_colour misc/utils/change_colour.cpp)
	add_executable(compress_dir misc/utils/compress_dir.cpp)
	add_executable(convert_model misc/utils/convert_model.cpp)
	add_executable(convert_tilemap misc/utils/convert_tilemap.cpp)
	add_executable(dump_a4_icon misc/utils/dump_a4_icon.cpp)
	add_executable(play_mml misc/utils/play_mml.cpp)
	add_executable(prune_sprite_json misc/utils/prune_sprite_json.cpp)
	add_executable(randtile misc/utils/randtile.cpp)
	add_executable(savetool misc/utils/savetool.c)
	add_executable(translate misc/utils/translate.cpp)
	add_executable(uncompress_cpa misc/utils/uncompress_cpa.cpp)
	if(WIN32)
		add_executable(pack_shader misc/utils/pack_shader.cpp)
	endif()
endif()

if(WANT_ALLEGRO_TOOLS)
	add_executable(mkpixelfont misc/utils/mkpixelfont.cpp)
endif()

if(USE_STATIC_LIBS)
	set(TGUI6_LIB tgui6)
else()
	set(TGUI6_LIB tgui6)
endif()

if(MINGW)
	if (DBG)
		SET(FLAGS "${FLAGS} -g") # -fsanitize=address -shared-libasan")
		SET(LFLAGS "${LFLAGS} -g") # -fsanitize=address -shared-libasan")
	endif()
	#add_custom_command(TARGET ${SHIM_LIB} POST_BUILD
	#COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_BINARY_DIR}/libshim5.dll.a ${CMAKE_BINARY_DIR}/libshim5.a
	#)

	if(USE_STATIC_LIBS)
		set(FLAGS "${FLAGS} -DTGUI6_STATIC")
	endif()
	if(USE_D3DX)
		set(FLAGS "${FLAGS} -DUSE_D3DX")
	endif()
	if(USE_PNG)
		set(FLAGS "${FLAGS} -DUSE_PNG")
	endif()
	if(WANT_XML)
		set(FLAGS "${FLAGS} -DUSE_XML")
	endif()
	if(USE_VORBIS)
		set(FLAGS "${FLAGS} -DUSE_VORBIS")
	endif()
	if(USE_VORBISFILE)
		set(FLAGS "${FLAGS} -DUSE_VORBISFILE")
	endif()
	if(USE_FLAC)
		set(FLAGS "${FLAGS} -DUSE_FLAC")
	endif()
	if(STEAMWORKS)
		set(FLAGS "${FLAGS} -DSTEAMWORKS")
	endif()
	if(NOT SHARED_LIB)
		set(FLAGS "${FLAGS} -DSHIM5_STATIC")
	endif()
	set(LIBS ${LIBS} mingw32 SDL3 SDL3_ttf winmm dbghelp ${TGUI6_LIB})
	if(USE_PNG)
		LIST(APPEND LIBS png16)
	endif()
	if(WANT_TTF)
		#LIST(APPEND LIBS freetype)
	endif()
	if(USE_VORBISFILE)
		LIST(APPEND LIBS vorbisfile vorbis)
	elseif(USE_VORBIS)
		LIST(APPEND LIBS vorbis)
	endif()
	if(USE_FLAC)
		LIST(APPEND LIBS FLAC)
	endif()
	if(USE_VORBISFILE OR USE_VORBIS OR USE_FLAC)
		LIST(APPEND LIBS ogg)
	endif()
	LIST(APPEND LIBS zlib)
	set_target_properties(${SHIM_LIB} PROPERTIES COMPILE_FLAGS "-DSHIM5_BUILD ${FLAGS}")
	set_target_properties(${SHIM_LIB} PROPERTIES LINK_FLAGS "${LFLAGS}")
	target_link_libraries(${SHIM_LIB} ${LIBS})
	if(WANT_EXAMPLES)
		set(EXAMPLE_LIBS ${LIBS} ${SHIM_LIB})
		set_target_properties(example PROPERTIES COMPILE_FLAGS "${FLAGS}")
		target_link_libraries(example ${EXAMPLE_LIBS})
	endif()
	if(WANT_TOOLS)
		set(TOOL_LIBS ${LIBS} ${SHIM_LIB})
		set_target_properties(change_colour PROPERTIES COMPILE_FLAGS "${FLAGS}")
		set_target_properties(change_colour PROPERTIES LINK_FLAGS "${LFLAGS}")
		target_link_libraries(change_colour ${TOOL_LIBS})
		set_target_properties(compress_dir PROPERTIES COMPILE_FLAGS "${FLAGS}")
		set_target_properties(compress_dir PROPERTIES LINK_FLAGS "${LFLAGS}")
		target_link_libraries(compress_dir ${TOOL_LIBS})
		set_target_properties(convert_model PROPERTIES COMPILE_FLAGS "${FLAGS}")
		set_target_properties(convert_model PROPERTIES LINK_FLAGS "${LFLAGS}")
		target_link_libraries(convert_model ${TOOL_LIBS})
		set_target_properties(convert_tilemap PROPERTIES COMPILE_FLAGS "${FLAGS}")
		set_target_properties(convert_tilemap PROPERTIES LINK_FLAGS "${LFLAGS}")
		target_link_libraries(convert_tilemap ${TOOL_LIBS})
		set_target_properties(dump_a4_icon PROPERTIES COMPILE_FLAGS "${FLAGS}")
		set_target_properties(dump_a4_icon PROPERTIES LINK_FLAGS "${LFLAGS}")
		target_link_libraries(dump_a4_icon ${TOOL_LIBS})
		set_target_properties(play_mml PROPERTIES COMPILE_FLAGS "${FLAGS}")
		set_target_properties(play_mml PROPERTIES LINK_FLAGS "${LFLAGS}")
		target_link_libraries(play_mml ${TOOL_LIBS})
		set_target_properties(prune_sprite_json PROPERTIES COMPILE_FLAGS "${FLAGS}")
		set_target_properties(prune_sprite_json PROPERTIES LINK_FLAGS "${LFLAGS}")
		target_link_libraries(prune_sprite_json ${TOOL_LIBS})
		set_target_properties(randtile PROPERTIES COMPILE_FLAGS "${FLAGS}")
		set_target_properties(randtile PROPERTIES LINK_FLAGS "${LFLAGS}")
		target_link_libraries(randtile ${TOOL_LIBS})
		set_target_properties(uncompress_cpa PROPERTIES COMPILE_FLAGS "${FLAGS}")
		set_target_properties(uncompress_cpa PROPERTIES LINK_FLAGS "${LFLAGS}")
		target_link_libraries(uncompress_cpa ${TOOL_LIBS})
		set_target_properties(savetool PROPERTIES COMPILE_FLAGS "${FLAGS}")
		set_target_properties(savetool PROPERTIES LINK_FLAGS "${LFLAGS}")
		target_link_libraries(savetool zlib)
		set_target_properties(pack_shader PROPERTIES COMPILE_FLAGS "${FLAGS}")
		set_target_properties(pack_shader PROPERTIES LINK_FLAGS "${LFLAGS}")
		target_link_libraries(pack_shader ${TOOL_LIBS})
	endif()
	if(WANT_ALLEGRO_TOOLS)
		set(ALLEGRO_LIBS "allegro_monolith-static" "freetype" "zlib" "opengl32" "dxguid" "dinput8" "xinput" "dsound" "kernel32" "user32" "gdi32" "comdlg32" "ole32" "winmm" "psapi" "gdiplus" "uuid" "shlwapi" "dbghelp")
		set_target_properties(mkpixelfont PROPERTIES COMPILE_FLAGS "${FLAGS}")
		target_link_libraries(mkpixelfont ${ALLEGRO_LIBS})
	endif()
elseif(WIN32)
	if(SHARED_LIB)
		set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /SUBSYSTEM:WINDOWS")
	else()
		set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /SUBSYSTEM:CONSOLE")
	endif()
	set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /ignore:4099")
	SET(FLAGS "/D_CRT_SECURE_NO_WARNINGS /D_USE_MATH_DEFINES /EHsc /MP /W3 /wd4244 /wd4800 /wd4091 /wd4101 /wd4065 /MT /Gy")
	SET(FLAGS "${FLAGS} /DNTDDI_VERSION=0x06010000 /D_WIN32_WINNT=0x601")
	if(USE_STATIC_LIBS)
		set(FLAGS "${FLAGS} /DTGUI6_STATIC")
	endif()
	if(USE_D3DX)
		set(FLAGS "${FLAGS} /DUSE_D3DX")
	endif()
	if(USE_PNG)
		set(FLAGS "${FLAGS} /DUSE_PNG")
	endif()
	if(WANT_XML)
		set(FLAGS "${FLAGS} /DUSE_XML")
	endif()
	if(USE_VORBIS)
		set(FLAGS "${FLAGS} /DUSE_VORBIS")
	endif()
	if(USE_VORBISFILE)
		set(FLAGS "${FLAGS} /DUSE_VORBISFILE")
	endif()
	if(USE_FLAC)
		set(FLAGS "${FLAGS} /DUSE_FLAC")
	endif()
	if(STEAMWORKS)
		set(FLAGS "${FLAGS} /DSTEAMWORKS")
	endif()
	if(SHARED_LIB)
		set(LIBS ${TGUI6_LIB} SDL3 SDL3_ttf winmm dbghelp)
		if(WANT_TTF)
			LIST(APPEND LIBS freetype zlibstatic)
		else()
			LIST(APPEND LIBS zlibstatic)
		endif()
		if(USE_VORBISFILE)
			LIST(APPEND LIBS libvorbisfile_static libvorbis_static ogg)
		endif()
		if(USE_VORBIS)
			LIST(APPEND LIBS libvorbis_static ogg)
		endif()
		if(USE_FLAC)
			LIST(APPEND LIBS ogg FLAC)
		endif()
		if(USE_PNG)
			LIST(APPEND LIBS libpng16_static)
		endif()
		set(PROGRAM_LIBS ${LIBS})
	else()
		set(FLAGS "${FLAGS} /DSHIM5_STATIC")
		set(PROGRAM_LIBS ${TGUI6_LIB} SDL3 SDL3_ttf winmm dbghelp)
		if(WANT_TTF)
			LIST(APPEND PROGRAM_LIBS freetype zlibstatic)
		else()
			LIST(APPEND PROGRAM_LIBS zlibstatic)
		endif()
		if(USE_VORBISFILE)
			LIST(APPEND PROGRAM_LIBS libvorbisfile_static libvorbis_static ogg)
		endif()
		if(USE_VORBIS)
			LIST(APPEND PROGRAM_LIBS libvorbis_static ogg)
		endif()
		if(USE_FLAC)
			LIST(APPEND PROGRAM_LIBS ogg FLAC)
		endif()
		if(USE_PNG)
			LIST(APPEND LIBS libpng16_static)
		endif()
	endif()
	target_link_libraries(${SHIM_LIB} ${LIBS})
	set_target_properties(${SHIM_LIB} PROPERTIES COMPILE_FLAGS "/DSHIM5_BUILD ${FLAGS}")
	if(WANT_EXAMPLES)
		set(EXAMPLE_LIBS ${SHIM_LIB} ${PROGRAM_LIBS})
		set_target_properties(example PROPERTIES COMPILE_FLAGS "${FLAGS}")
		target_link_libraries(example ${EXAMPLE_LIBS})
	endif()
	if(WANT_TOOLS)
		set(TOOL_LIBS ${SHIM_LIB} ${PROGRAM_LIBS})
		set_target_properties(change_colour PROPERTIES COMPILE_FLAGS "${FLAGS}")
		target_link_libraries(change_colour ${TOOL_LIBS})
		set_target_properties(compress_dir PROPERTIES COMPILE_FLAGS "${FLAGS}")
		target_link_libraries(compress_dir ${TOOL_LIBS})
		set_target_properties(convert_model PROPERTIES COMPILE_FLAGS "${FLAGS}")
		target_link_libraries(convert_model ${TOOL_LIBS})
		set_target_properties(convert_tilemap PROPERTIES COMPILE_FLAGS "${FLAGS}")
		target_link_libraries(convert_tilemap ${TOOL_LIBS})
		set_target_properties(dump_a4_icon PROPERTIES COMPILE_FLAGS "${FLAGS}")
		target_link_libraries(dump_a4_icon ${TOOL_LIBS})
		set_target_properties(play_mml PROPERTIES COMPILE_FLAGS "${FLAGS}")
		target_link_libraries(play_mml ${TOOL_LIBS})
		set_target_properties(prune_sprite_json PROPERTIES COMPILE_FLAGS "${FLAGS}")
		target_link_libraries(prune_sprite_json ${TOOL_LIBS})
		set_target_properties(randtile PROPERTIES COMPILE_FLAGS "${FLAGS}")
		target_link_libraries(randtile ${TOOL_LIBS})
		set_target_properties(uncompress_cpa PROPERTIES COMPILE_FLAGS "${FLAGS}")
		target_link_libraries(uncompress_cpa ${TOOL_LIBS})
		set_target_properties(savetool PROPERTIES COMPILE_FLAGS "${FLAGS}")
		target_link_libraries(savetool zlibstatic)
		if(WIN32)
			set_target_properties(pack_shader PROPERTIES COMPILE_FLAGS "${FLAGS}")
			target_link_libraries(pack_shader ${TOOL_LIBS})
		endif()
	endif()
	if(WANT_ALLEGRO_TOOLS)
		set(ALLEGRO_LIBS "allegro_monolith-static" "freetype" "zlibstatic" "opengl32" "dxguid" "dinput8" "xinput" "dsound" "kernel32" "user32" "gdi32" "comdlg32" "ole32" "winmm" "psapi" "gdiplus" "uuid" "shlwapi" "dbghelp")
		set_target_properties(mkpixelfont PROPERTIES COMPILE_FLAGS "${FLAGS}")
		target_link_libraries(mkpixelfont ${ALLEGRO_LIBS})
	endif()
endif()
